services:
  postgres:
    image: postgres
    restart: no
    networks:
      - vitfit
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password3000!!
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - vitfit-pgdata:/var/lib/postgresql/data
networks:
  vitfit:
    external: true
volumes:
  vitfit-pgdata:
    external: true