services:
  postgres:
    image: postgres
    restart: never
    # see networks section below
    # networks:
    #   - postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password3000!!
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    # volumes:
    #   - vitfit-pgdata:/var/lib/postgresql/data
# networks:
#   postgresql:
#     this can be commented out if not needed but it is useful to have a network for other dockers communicating with this PostgreSQL
#     external: true
# volumes:
#   vitfit-pgdata:
#     external: true